INSERT INTO TODO_LIST (WHAT, WHEN) VALUES ('Collect underpants.', '2016-08-10');
INSERT INTO TODO_LIST (WHAT) VALUES ('???????');
INSERT INTO TODO_LIST (WHAT, WHEN) VALUES ('PROFIT!!!', '2016-08-12');